export const users = [
  { userName: "user1", name: "کاربر 1" },
  { userName: "user2", name: "کاربر 2" },
  { userName: "user3", name: "کاربر 3" },
  { userName: "user4", name: "کاربر 4" },
  { userName: "user5", name: "کاربر 5" },
];

export const initialItems = [
  {
    category: "user1",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "1",
    price: "7676",
    title: "پروژه",
    type: "income",
    editMode: false,
  },
  {
    category: "user1",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "2",
    price: "7676",
    title: "پروژه",
    type: "income",
    editMode: false,
  },
  {
    category: "user1",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "3",
    price: "7676",
    title: "پروژه",
    type: "income",
    editMode: false,
  },
  {
    category: "user1",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "4",
    price: "7676",
    title: "پروژه",
    type: "income",
    editMode: false,
  },
  {
    category: "user2",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "5",
    price: "7676",
    title: "پروژه",
    type: "income",
    editMode: false,
  },
  {
    category: "user2",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "6",
    price: "7676",
    title: "پروژه",
    type: "income",
    editMode: false,
  },
  {
    category: "user2",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "7",
    price: "7676",
    title: "پروژه",
    type: "income",
    editMode: false,
  },
  {
    category: "user3",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "8",
    price: "7676",
    title: "پروژه",
    type: "income",
    editMode: false,
  },
  {
    category: "user3",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "9",
    price: "7676",
    title: "حقوق شرکت",
    type: "income",
    editMode: false,
  },
  {
    category: "user3",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "10",
    price: "1212",
    title: "پرداخت حق بیمه",
    type: "cost",
    editMode: false,
  },
  {
    category: "user4",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "11",
    price: "4242",
    title: "ویزیت دندانپزشک",
    type: "cost",
    editMode: false,
  },
  {
    category: "user4",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "12",
    price: "4343",
    title: "تعمیر ماشین",
    type: "cost",
    editMode: false,
  },
  {
    category: "user3",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "13",
    price: "6565",
    title: "شهریه دانشگاه",
    type: "cost",
    editMode: false,
  },
  {
    category: "user5",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "14",
    price: "6767",
    title: "پرداخت قبض اینترنت",
    type: "cost",
    editMode: false,
  },
  {
    category: "user5",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "15",
    price: "2323",
    title: "خرید ماوس",
    type: "cost",
    editMode: false,
  },
  {
    category: "user3",
    date: "۱۳۹۹/۱۱/۲۷",
    id: "16",
    price: "1212",
    title: "خرید کیف ورزشی",
    type: "cost",
    editMode: false,
  },
];
